apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: my-templates
  description: My organization templates
spec:
  targets:
    - ./catalog/system.yaml
    - ./catalog/llm-api.yaml
    - ./templates/python-fastapi/template.yaml
    - ./templates/website-with-chatbot/template.yaml

