apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources here are managed by ArgoCD.
# The ArgoCD Application is created by the RHDH template with createNamespace: true,
# so the namespace is created automatically on first sync.

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
  - pipeline.yaml
  - triggerbinding.yaml
  - triggertemplate.yaml
  - eventlistener.yaml
  - eventlistener-route.yaml
