apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: ${{ values.appName }}-template
  namespace: ${{ values.appName }}
spec:
  params:
  - name: git-repo-url
  - name: git-revision
    default: main
  resourcetemplates:
  - apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: ${{ values.appName }}-
      namespace: ${{ values.appName }}
      labels:
        app.kubernetes.io/instance: ${{ values.appName }}
        backstage.io/kubernetes-id: ${{ values.appName }}
        pipeline.openshift.io/strategy: docker
        pipeline.openshift.io/type: kubernetes
        tekton.dev/pipeline: ${{ values.appName }}
    spec:
      pipelineRef:
        name: ${{ values.appName }}
      params:
      - name: APP_NAME
        value: ${{ values.appName }}
      - name: GIT_REPO
        value: $(tt.params.git-repo-url)
      - name: GIT_REVISION
        value: $(tt.params.git-revision)
      - name: IMAGE_NAME
        value: image-registry.openshift-image-registry.svc:5000/${{ values.appName }}/${{ values.appName }}
      - name: GIT_K8_REPO
        value: https://github.com/${{ values.githubOrg }}/${{ values.appName }}-k8.git
      - name: PATH_CONTEXT
        value: .
      taskRunTemplate:
        serviceAccountName: pipeline
      timeouts:
        pipeline: 1h0m0s
      workspaces:
      - name: workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
      - name: k8-workspace
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
