apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.appName }}
    app.kubernetes.io/component: ${{ values.appName }}
    app.kubernetes.io/instance: ${{ values.appName }}
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/part-of: ${{ values.appName }}
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 22-minimal-ubi10
  name: ${{ values.appName }}
  namespace: ${{ values.namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
  selector:
    app: ${{ values.appName }}
    deployment: ${{ values.appName }}
