apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: ${{ values.appName }}-binding
  namespace: ${{ values.namespace }}
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
