schemaVersion: 2.2.2
metadata:
  name: ${{ values.appName }}
components:
  - name: python
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:3.28
      volumeMounts:
        - name: venv
          path: /home/user/.venv
      memoryLimit: '2Gi'
      memoryRequest: '1Gi'
      cpuLimit: '2'
      cpuRequest: '1'
      mountSources: true
  - name: venv
    volume:
      size: 1G
commands:
  - id: run
    exec:
      label: "Run the application"
      component: python
      workingDir: ${PROJECTS_ROOT}/${{ values.appName }}-code
      commandLine: python -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt && uvicorn main:app --reload --host 0.0.0.0 --port 8000
      group:
        kind: run
        isDefault: true
