schemaVersion: 2.3.0
metadata:
  name: ${{ values.appName }}
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryRequest: 1Gi
      memoryLimit: 8Gi
      cpuLimit: '4'
      cpuRequest: '0.5'
      endpoints:
        - name: app
          targetPort: 8080
          exposure: public
          protocol: http
          secure: true
commands:
  - id: install
    exec:
      component: tools
      commandLine: npm install
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: build
        isDefault: true
  - id: run
    exec:
      component: tools
      commandLine: npm start
      workingDir: ${PROJECT_SOURCE}
      group:
        kind: run
        isDefault: true
