apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.appName }}
  title: ${{ values.appName }}
  description: Node.js website with LLM-powered chatbot
  annotations:
    gitlab.com/project-slug: ${{ values.gitlabGroup }}/${{ values.appName }}-code
    backstage.io/source-location: url:${{ values.gitlabUrl }}/${{ values.gitlabGroup }}/${{ values.appName }}-code
    backstage.io/kubernetes-id: ${{ values.appName }}
    backstage.io/kubernetes-namespace: ${{ values.namespace }}
    argocd/app-name: ${{ values.appName }}
    argocd/instance-name: main
    janus-idp.io/tekton: ${{ values.appName }}
    dev.loft.sh/open-in-dev-spaces: ${{ values.gitlabUrl }}/${{ values.gitlabGroup }}/${{ values.appName }}-code
  links:
    - url: https://devspaces.${{ values.clusterAppDomain }}/#${{ values.gitlabUrl }}/${{ values.gitlabGroup }}/${{ values.appName }}-code
      title: Open in Dev Spaces
      icon: web
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: lux-and-living
  consumesApis:
    - lux-living-llm-api
