apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.appName }}
  namespace: rhdh-gitops
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    backstage.io/kubernetes-id: ${{ values.appName }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: ${{ values.gitlabUrl }}/${{ values.gitlabGroup }}/${{ values.appName }}-k8.git
    targetRevision: main
    path: k8
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
